### ISSUE TITLE
doesn't work with ember files type

### ISSUE THREAD

**Issue by ryadav** [rstacruz/sparkup#128]
Please correct so I can expand markup inside ember.js files i.e (*.hbs)

**Comment by faceleg** [comment]
We accept pull requests 👍🏽

**Comment by ryadav** [comment]
Sure I am up to the task, any pointers?

**Comment by rstacruz** [comment]
can you find out what the `filetype` is? (`:echo &filetype`)

**Comment by ryadav** [comment]
it's blank, I am getting by using set filetype=html, if you give me an idea what's need to be done i can try correcting it on my side and send in the change(s)
