### ISSUE TITLE
Sparkup with Javascript

### ISSUE THREAD

**Issue by xavierartot** [rstacruz/sparkup#132]
Hi,
I'm using React, how can I use it with .jsx and js?

Thanks

**Comment by rstacruz** [comment]
Unfortunately sparkup doesn't support jsx :\

**Comment by hilkins** [comment]
Is there any other tool that would do the trick ?

**Comment by abidibo** [comment]
@hilkins , I've just found this plugin: https://github.com/mattn/emmet-vim

**Comment by xavierartot** [comment]
It works with Javascript, but in jsx syntaxe I would like to replace class by className?
```
"sparkup
augroup sparkup_types
  " Remove ALL autocommands of the current group.
  autocmd!
  " Add sparkup to new filetypes
  autocmd FileType mustache,php,javascript,jsx runtime! ftplugin/html/sparkup.vim
augroup END
```

**Comment by xavierartot** [comment]
I can do that many words...
`h4[className=tagline]`
EDIT: I switched to Emmet...
