### ISSUE TITLE
Can i change double quote to single quote

### ISSUE THREAD

**Issue by jadeydi** [rstacruz/sparkup#87]
when input div.spark
how can i change
<div class="spark"></div>
to
<div class='spark'></div>

**Comment by mjacobus** [comment]
Hi @dlee 

Were you able to fix that? I also have annoying single quotes for attributes.

**Comment by dlee** [comment]
@mjacobus No, I haven't used sparkup since the last time I commented.

**Comment by mjacobus** [comment]
@dlee turns out that I was [using](https://github.com/mjacobus/.dotfiles/commit/1e152cf6cff73fa43c7d1fac4f70bf850e9eb8a4) `trinsten/vim-sparkup` instead of `stacruz/sparkup`. Maybe you did the same?
